<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EMOQPA6" failures="0" tests="14" name="com.ciranet.loginpage.testcases.LoginPageTest" time="0.000" errors="3" timestamp="2024-11-18T16:45:46 IST" skipped="11">
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="verifyLoginPageTitle" time="0.000">
    <skipped/>
  </testcase> <!-- verifyLoginPageTitle -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="verifyLoginPageComponents" time="0.000">
    <skipped/>
  </testcase> <!-- verifyLoginPageComponents -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="verifyValidLogin" time="0.000">
    <error message="java.lang.RuntimeException: User does not exist: null. Stopping the test." type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: User does not exist: null. Stopping the test.
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:57)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)
at org.testng.internal.Parameters.handleParameters(Parameters.java:803)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:924)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: User does not exist: null. Stopping the test.
at com.ciranet.testbase.TestBase.credentialsUserProvider(TestBase.java:247)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)
... 25 more
]]>
    </error>
  </testcase> <!-- verifyValidLogin -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="verifyValidLoginEnterKeyPress" time="0.000">
    <error message="java.lang.RuntimeException: User does not exist: null. Stopping the test." type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: User does not exist: null. Stopping the test.
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:57)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)
at org.testng.internal.Parameters.handleParameters(Parameters.java:803)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:924)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: User does not exist: null. Stopping the test.
at com.ciranet.testbase.TestBase.credentialsUserProvider(TestBase.java:247)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)
... 25 more
]]>
    </error>
  </testcase> <!-- verifyValidLoginEnterKeyPress -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="clickBrowserBackTest" time="0.000">
    <error message="java.lang.RuntimeException: User does not exist: null. Stopping the test." type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: java.lang.RuntimeException: User does not exist: null. Stopping the test.
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:57)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:157)
at org.testng.internal.Parameters.handleParameters(Parameters.java:803)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:924)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: User does not exist: null. Stopping the test.
at com.ciranet.testbase.TestBase.credentialsUserProvider(TestBase.java:247)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:53)
... 25 more
]]>
    </error>
  </testcase> <!-- clickBrowserBackTest -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="InvalidUserValidPassword" time="0.000">
    <skipped/>
  </testcase> <!-- InvalidUserValidPassword -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="validUserInvalidPassword" time="0.000">
    <skipped/>
  </testcase> <!-- validUserInvalidPassword -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="InvalidUserInvalidPassword" time="0.000">
    <skipped/>
  </testcase> <!-- InvalidUserInvalidPassword -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="showPasswordFunctionality" time="0.000">
    <skipped/>
  </testcase> <!-- showPasswordFunctionality -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="emptyUserEmptyPassword" time="0.000">
    <skipped/>
  </testcase> <!-- emptyUserEmptyPassword -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="VerifyChooseDifferentPortal" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyChooseDifferentPortal -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="VerifyForgotPasswordButtonClick" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyForgotPasswordButtonClick -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="VerifyForgotPasswordPageComponents" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyForgotPasswordPageComponents -->
  <system-out/>
  <testcase classname="com.ciranet.loginpage.testcases.LoginPageTest" name="verifyLogout" time="0.000">
    <skipped/>
  </testcase> <!-- verifyLogout -->
  <system-out/>
</testsuite> <!-- com.ciranet.loginpage.testcases.LoginPageTest -->
